
const houses=[
['40 Greek Street','London, UK','14 FEB 2026','oxblood','40','Grade II Georgian townhouse','The original Soho House opened in 1995, set across three floors of a Grade II-listed townhouse in London’s Soho.','I belong in rooms that make space for me.',true,'houses-greek.webp','https://www.sohohouse.com/houses/soho-house-40-greek-street',['Caught up with Eli at the Circle Bar, then met two designers through the next table. One of those easy Soho nights that ended with plans in the diary.','Came in with a noisy week behind me and left feeling reset. The House was busy, but somehow calm.','Dinner turned into conversations about cities, work and where to go next. Properly good company.'],['Circle Bar','House menu','Daily events','Terraces']],
['White City House','London, UK','03 APR 2026','ink','WCH','BBC Television Centre','Set in the former BBC Television Centre, White City House carries the building’s broadcast-era architecture into a members’ club.','I make room for a new point of view.',true,'houses-white-city.webp','https://www.sohohouse.com/houses/white-city-house',['A swim before Sunday lunch did the job. Slow afternoon, good food and no rush to be anywhere else.','Met a filmmaker after a screening and ended up talking creative ideas until close. That is why I keep coming back.','Worked from the lounge, then stayed for a drink. The day shifted gears without needing to leave.'],['45 bedrooms','Rooftop pool','3 screening rooms','Gym, pool & sauna']],
['Soho Farmhouse','Oxfordshire, UK','21 JUN 2026','moss','SF','Cabins and lake','An Oxfordshire countryside retreat of cabins, lakes and long lunches, made for switching off without disappearing.','I let the good things take their time.',true,'houses-farmhouse.webp','https://www.sohohouse.com/houses/soho-farmhouse',['A long walk before breakfast, then coffee by the lake. The right kind of quiet.','Clay shooting with people I had only just met. By dinner it felt like an old group.','A proper reset: fresh air, great food and enough space to think clearly again.'],['114 cabins & bedrooms','Spa & gym','Indoor & outdoor pools','Lake hot tubs','Riding, clay, tennis & padel']],
['Babington House','Somerset, UK','Awaiting a visit','blank','BH','Georgian manor','A Somerset House with its own gardens, cinema, spa and bedrooms—an enduring country escape for members.','Something wonderful is waiting for me.',false,'houses-babington.webp','https://www.sohohouse.com/houses/babington-house',[],['33 bedrooms','Indoor & outdoor pools','Gym & spa','Reformer Pilates','Cricket, padel & tennis']],
['High Road House','London, UK','Awaiting a visit','blank','HRH','Edwardian townhouse','A west London House in a period building, with bedrooms and spaces for members to eat, drink and gather.','I follow the roads that feel like mine.',false,'houses-high-road.webp','https://www.sohohouse.com/houses/high-road-house',[],['14 bedrooms','High Road Brasserie','Member events','Private dining']],
['Soho House Bangkok','Bangkok, Thailand','Awaiting a visit','blank','BKK','Former Eugenia Hotel','Set across three floors of the former Eugenia Hotel in Sukhumvit, surrounded by tropical foliage with a 12m pool and terrace.','I make space for the unfamiliar to become mine.',false,'houses-bangkok.webp','https://www.sohohouse.com/houses/soho-house-bangkok',[],['12m outdoor pool','Pool terrace','3 bars','Members’ restaurant','Member events']],
['Soho House Barcelona','Barcelona, Spain','Awaiting a visit','blank','BCN','Gothic Quarter rooftop','In Barcelona’s Gothic Quarter, the House has 56 bedrooms and a rooftop pool overlooking Marina Port Vell.','I follow the light toward new horizons.',false,'houses-barcelona.webp','https://www.sohohouse.com/houses/soho-house-barcelona',[],['56 bedrooms','Rooftop & indoor pools','Gym & spin studio','Cowshed spa','Screening room']],
['Soho House New York','New York, USA','Awaiting a visit','blank','NYC','Meatpacking District','A Manhattan House in the Meatpacking District, with a Drawing Room, Dining Room and spaces for screenings and celebrations.','I arrive ready for what the city gives back.',false,'houses-new-york.webp','https://www.sohohouse.com/houses/soho-house-new-york',[],['44 bedrooms','Rooftop pool','44-seat screening room','Drawing Room','Dining Room']],
['Soho House Mumbai','Mumbai, India','Awaiting a visit','blank','BOM','Juhu Beach townhouse','An 11-storey townhouse on Juhu Beach, with 38 bedrooms, a rooftop pool, screening room and interiors rooted in Indian craft.','I carry curiosity wherever I go.',false,'houses-mumbai.webp','https://www.sohohouse.com/houses/soho-house-mumbai',[],['38 bedrooms','Rooftop pool','Gym','32-seat screening room','Cecconi’s']],
['Soho House Mexico City','Mexico City, Mexico','Awaiting a visit','blank','CDMX','Baroque-inspired casa','Soho House’s first Latin American location: a Baroque-inspired casa in Colonia Juárez with a tequila bar and its largest pool in the Americas.','I let each place change the way I see.',false,'houses-mexico-city.webp','https://www.sohohouse.com/houses/soho-house-mexico-city',[],['Outdoor pool','Outdoor gym','Padel & pickleball','Tequila bar','Member events']]
];
const cityStamps=[
['London','city-stamps/london.webp'],['Somerset','city-stamps/somerset.webp'],['Brighton','city-stamps/brighton.webp'],['Oxfordshire','city-stamps/oxfordshire.webp'],['Manchester','city-stamps/manchester.webp'],['Windsor','city-stamps/windsor.webp'],['Amsterdam','city-stamps/amsterdam.webp'],['Barcelona','city-stamps/barcelona.webp'],['Berlin','city-stamps/berlin.webp'],['Ibiza','city-stamps/ibiza.webp'],['Istanbul','city-stamps/istanbul.webp'],['Copenhagen','city-stamps/copenhagen.webp'],['Paris','city-stamps/paris.webp'],['Rome','city-stamps/rome.webp'],['Stockholm','city-stamps/stockholm.webp'],['Mykonos','city-stamps/mykonos.webp'],['Austin','city-stamps/austin.webp'],['Chicago','city-stamps/chicago.webp'],['Los Angeles','city-stamps/los-angeles.webp'],['New York','city-stamps/new-york.webp'],['Miami','city-stamps/miami.webp'],['Canouan','city-stamps/canouan.webp'],['Mexico City','city-stamps/mexico-city.webp'],['Nashville','city-stamps/nashville.webp'],['Portland','city-stamps/portland.webp'],['São Paulo','city-stamps/sao-paulo.webp'],['Toronto','city-stamps/toronto.webp'],['Mumbai','city-stamps/mumbai.webp'],['Bangkok','city-stamps/bangkok.webp'],['Hong Kong','city-stamps/hong-kong.webp'],['Tokyo','city-stamps/tokyo.webp']
];
const stampPositions=['left:-19px;top:4%;transform:rotate(-8deg)','right:-17px;top:3%;transform:rotate(7deg)','left:2%;top:18%;transform:rotate(5deg)','right:1%;top:19%;transform:rotate(-6deg)','left:-13px;top:34%;transform:rotate(9deg)','right:-15px;top:36%;transform:rotate(-9deg)','left:2%;top:51%;transform:rotate(-4deg)','right:2%;top:52%;transform:rotate(5deg)','left:-18px;top:67%;transform:rotate(8deg)','right:-17px;top:68%;transform:rotate(-7deg)','left:3%;top:82%;transform:rotate(-6deg)','right:2%;top:82%;transform:rotate(8deg)','left:9%;top:-26px;transform:rotate(5deg)','right:9%;top:-26px;transform:rotate(-6deg)','left:20%;top:calc(100% - 64px);transform:rotate(-7deg)','right:20%;top:calc(100% - 64px);transform:rotate(8deg)','left:13%;top:27%;transform:rotate(-11deg)','right:12%;top:28%;transform:rotate(10deg)','left:11%;top:61%;transform:rotate(8deg)','right:11%;top:61%;transform:rotate(-9deg)','left:30%;top:1%;transform:rotate(-5deg)','right:30%;top:1%;transform:rotate(6deg)','left:33%;top:calc(100% - 76px);transform:rotate(8deg)','right:33%;top:calc(100% - 76px);transform:rotate(-7deg)','left:5%;top:43%;transform:rotate(6deg)','right:5%;top:44%;transform:rotate(-5deg)','left:24%;top:10%;transform:rotate(-9deg)','right:24%;top:10%;transform:rotate(9deg)','left:24%;top:75%;transform:rotate(6deg)','right:24%;top:75%;transform:rotate(-8deg)','left:42%;top:1%;transform:rotate(4deg)','right:42%;top:calc(100% - 77px);transform:rotate(-5deg)'];
const landmarkStamps=[['London','landmark-stamps/london.jpg'],['Bangkok','landmark-stamps/bangkok.jpg'],['Barcelona','landmark-stamps/barcelona.jpg'],['New York','landmark-stamps/new-york.jpg'],['Paris','landmark-stamps/paris.jpg'],['Rome','landmark-stamps/rome.jpg']];const landmarkPositions=['left:-26px;top:10%;transform:rotate(-8deg)','left:1%;top:42%;transform:rotate(6deg)','left:-18px;top:74%;transform:rotate(-5deg)','right:-25px;top:8%;transform:rotate(7deg)','right:1%;top:42%;transform:rotate(-6deg)','right:-20px;top:73%;transform:rotate(8deg)'];
const edgeStamps=document.querySelector('.edge-stamps');function renderCityStamps(){edgeStamps.innerHTML='';landmarkStamps.slice().sort(()=>Math.random()-.5).forEach(([city,image],index)=>{const stamp=document.createElement('div');stamp.className='edge-stamp';stamp.style.cssText=landmarkPositions[index];stamp.innerHTML='<img src="'+image+'" alt=""><span class="stamp-city"><i>1ST</i><b>'+city+'</b><span>SH</span></span>';edgeStamps.appendChild(stamp)})}renderCityStamps();const grid=document.querySelector('#grid'),dossier=document.querySelector('#dossier'),content=document.querySelector('#dossier-content'),notes=JSON.parse(localStorage.getItem('soho-passport-notes')||'{}');let trigger,current;
const atlasPlaces={
  '40 Greek Street':{city:'London',country:'United Kingdom',code:'LDN',pin:[50,34],card:[30,20],tilt:-4},
  'White City House':{city:'London',country:'United Kingdom',code:'LDN',pin:[50,34],card:[30,20],tilt:-4},
  'Soho Farmhouse':{city:'Oxfordshire',country:'United Kingdom',code:'OXF',pin:[48,30],card:[61,48],tilt:4},
  'Babington House':{city:'Somerset',country:'United Kingdom',code:'SOM',pin:[46,37],card:[60,56],tilt:-3},
  'High Road House':{city:'London',country:'United Kingdom',code:'LDN',pin:[50,34],card:[30,20],tilt:-4},
  'Soho House Bangkok':{city:'Bangkok',country:'Thailand',code:'BKK',pin:[74,53],card:[73,65],tilt:3},
  'Soho House Barcelona':{city:'Barcelona',country:'Spain',code:'BCN',pin:[48,42],card:[35,54],tilt:3},
  'Soho House New York':{city:'New York',country:'United States',code:'NYC',pin:[31,39],card:[14,27],tilt:-5},
  'Soho House Mumbai':{city:'Mumbai',country:'India',code:'BOM',pin:[67,51],card:[66,31],tilt:4},
  'Soho House Mexico City':{city:'Mexico City',country:'Mexico',code:'CDMX',pin:[20,53],card:[13,65],tilt:-3}
};
const worldPage=document.createElement('section');worldPage.className='page world-board';worldPage.id='world';worldPage.setAttribute('aria-labelledby','world-title');worldPage.innerHTML=`<header class="world-ledger"><div><span class="eyebrow">Member map / lived places</span><h1 id="world-title">A world, <em>made personal.</em></h1></div><p id="world-count"></p></header><section class="world-atlas" aria-label="Member House world map"><svg class="atlas-globe" viewBox="0 0 100 70" role="img" aria-label="Illustrated globe"><circle class="orb" cx="50" cy="35" r="31"/><ellipse class="longitude" cx="50" cy="35" rx="15" ry="31"/><ellipse class="longitude" cx="50" cy="35" rx="25" ry="31"/><path class="latitude" d="M19 35h62M22 23h56M22 47h56M30 13h40M30 57h40"/><path class="land" d="M31 19l5-5 8 1 3 5-2 5 5 4-1 5-5 1-3 6-5-1-1-6-5-4 2-5-5-2z"/><path class="land" d="M50 18l8-2 6 4 7 1 5 5-2 4-7-2-4 5-7 1-3 5-5-3 2-6-3-4z"/><path class="land" d="M49 36l5 3 3 8 5 6-2 8-5 1-3-8-5-6 1-6z"/><path class="land minor" d="M69 47l5 3 2 5-3 4-6-1-2-5 4-6zM22 25l-4 2-2 5 3 3 4-2 1-5zM75 19l4 1 3 4-2 3-5-1-2-4z"/></svg><div class="atlas-pins" id="atlas-pins"></div><div class="atlas-caption">City stamps unlock your archive</div><div class="atlas-key">Pins show every country chapter</div></section>`;document.querySelector('#profile').insertAdjacentElement('afterend',worldPage);document.querySelector('.tabs').insertAdjacentHTML('beforeend','<button class="tab" data-page="world">World</button>');
function renderWorldBoard(){const host=document.querySelector('#atlas-pins'),visited=houses.filter(h=>h[8]&&atlasPlaces[h[0]]),groups=Object.values(visited.reduce((all,house)=>{const place=atlasPlaces[house[0]],key=place.city;(all[key]||(all[key]={...place,houses:[]})).houses.push(house);return all},{}));const countries=new Set(groups.map(group=>group.country));document.querySelector('#world-count').innerHTML='<b>'+String(countries.size).padStart(2,'0')+'</b>'+String(countries.size===1?'country':'countries')+' · '+String(groups.length).padStart(2,'0')+' cities';if(!groups.length){host.innerHTML='<div class="atlas-empty"><div><b>Your first pin is waiting.</b><span>Visit a House to begin the map</span></div></div>';return}host.innerHTML=groups.map(group=>{const primary=group.houses[0],memoryCount=group.houses.reduce((total,house)=>total+house[11].length+(notes[house[0]]||[]).length,0),[pinX,pinY]=group.pin,[cardX,cardY]=group.card;return '<div class="atlas-entry"><svg class="atlas-thread" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><line x1="'+pinX+'" y1="'+pinY+'" x2="'+cardX+'" y2="'+cardY+'"/></svg><i class="atlas-pin" style="left:'+pinX+'%;top:'+pinY+'%"></i><button class="atlas-stamp" style="left:'+cardX+'%;top:'+cardY+'%;--tilt:'+group.tilt+'deg" aria-label="Open '+group.city+' House archive"><small>'+group.country+' · '+group.houses.length+' '+(group.houses.length===1?'House':'Houses')+'</small><strong>'+group.code+'</strong><span>'+group.city+'</span><em>'+memoryCount+'</em></button></div>'}).join('');host.querySelectorAll('.atlas-stamp').forEach((stamp,index)=>stamp.onclick=()=>openHouse(groups[index].houses[0],stamp))}
renderWorldBoard();
function escape(s){return s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const shell=document.querySelector('.shell'),focusableSelector='a[href],button:not([disabled]),textarea:not([disabled]),input:not([disabled]),[tabindex]:not([tabindex="-1"])',acceptedPhotoTypes=new Set(['image/jpeg','image/png','image/webp','image/gif']),maxPhotoBytes=8*1024*1024;
function prepareUpload(){const file=document.querySelector('#file'),slot=document.querySelector('.photo-slot');if(!file||!slot)return;file.accept='image/jpeg,image/png,image/webp,image/gif';if(!document.querySelector('#upload-status'))slot.insertAdjacentHTML('afterend','<p class="upload-status" id="upload-status" role="status" aria-live="polite"></p>')}
function updateDossierState(){const shown=dossier.classList.contains('show');shell.inert=shown;if(shown){shell.setAttribute('aria-hidden','true');prepareUpload();requestAnimationFrame(()=>document.querySelector('#close').focus())}else shell.removeAttribute('aria-hidden')}
new MutationObserver(updateDossierState).observe(dossier,{attributes:true,attributeFilter:['class']});
window.addEventListener('keydown',event=>{if(event.key!=='Tab'||!dossier.classList.contains('show'))return;const controls=[...dossier.querySelectorAll(focusableSelector)].filter(control=>!control.hidden);const first=controls[0],last=controls.at(-1);if(!first)return;if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}});
function openCityArchive(group,from){trigger=from;current=null;seal.textContent=group.code;document.querySelector('#dossier-kicker').textContent='YOUR CITY ARCHIVE · '+group.country;document.querySelector('#dossier-title').textContent=group.city+' chapter';document.querySelector('#affirm').textContent='“Every House becomes part of the story.”';content.innerHTML='<section class="archive-intro"><span class="eyebrow">Choose a House</span><p>'+group.houses.length+' Houses · '+group.houses.reduce((total,house)=>total+house[11].length+(notes[house[0]]||[]).length,0)+' memories</p></section><section class="city-archive">'+group.houses.map((house,index)=>'<button class="city-house" data-city-house="'+index+'"><img src="'+house[9]+'" alt=""><span><small>'+house[2]+'</small><b>'+house[0]+'</b><em>'+house[11].length+(notes[house[0]]||[]).length+' memories</em></span><i>Open ↗</i></button>').join('')+'</section>';content.querySelectorAll('[data-city-house]').forEach((button,index)=>button.onclick=()=>openHouse(group.houses[index],button));dossier.classList.add('show');requestAnimationFrame(()=>content.querySelector('[data-city-house]').focus())}
function renderWorldBoardUpdated(){const host=document.querySelector('#atlas-pins'),visited=houses.filter(h=>h[8]&&atlasPlaces[h[0]]),groups=Object.values(visited.reduce((all,house)=>{const place=atlasPlaces[house[0]],key=place.city;(all[key]||(all[key]={...place,houses:[]})).houses.push(house);return all},{})),countries=new Set(groups.map(group=>group.country));document.querySelector('#world-count').innerHTML='<b>'+String(countries.size).padStart(2,'0')+'</b>'+String(countries.size===1?'country':'countries')+' · '+String(groups.length).padStart(2,'0')+' cities';if(!groups.length){host.innerHTML='<div class="atlas-empty"><div><b>Your first pin is waiting.</b><span>Visit a House to begin the map</span></div></div>';return}host.innerHTML=groups.map(group=>{const memoryCount=group.houses.reduce((total,house)=>total+house[11].length+(notes[house[0]]||[]).length,0),[pinX,pinY]=group.pin,[cardX,cardY]=group.card;return '<div class="atlas-entry"><svg class="atlas-thread" viewBox="0 0 100 100" preserveAspectRatio="none" aria-hidden="true"><line x1="'+pinX+'" y1="'+pinY+'" x2="'+cardX+'" y2="'+cardY+'"/></svg><i class="atlas-pin" style="left:'+pinX+'%;top:'+pinY+'%"></i><button class="atlas-stamp" style="left:'+cardX+'%;top:'+cardY+'%;--tilt:'+group.tilt+'deg" aria-label="Open '+group.city+' House archive"><small>'+group.country+' · '+group.houses.length+' '+(group.houses.length===1?'House':'Houses')+'</small><strong>'+group.code+'</strong><span>'+group.city+'</span><em>'+memoryCount+'</em></button></div>'}).join('');host.querySelectorAll('.atlas-stamp').forEach((stamp,index)=>stamp.onclick=()=>{const group=groups[index];group.houses.length===1?openHouse(group.houses[0],stamp):openCityArchive(group,stamp)})}
renderWorldBoard=renderWorldBoardUpdated;
const atlasSvg=document.querySelector('.atlas-globe');atlasSvg.setAttribute('viewBox','0 0 1000 500');atlasSvg.innerHTML=`<defs><pattern id="atlas-hatch" width="8" height="8" patternUnits="userSpaceOnUse" patternTransform="rotate(-31)"><rect width="8" height="8" fill="rgba(225,202,151,.12)"/><line x1="0" y1="0" x2="0" y2="8" stroke="rgba(245,226,185,.52)" stroke-width=".8"/></pattern></defs><rect class="flat-frame" x="8" y="8" width="984" height="484"/><path class="flat-land" d="M48 144l23-25 28-4 15-25 40-17 44 8 27 20 31 8 19 24-10 27-22 7-16 28-29 7-20 26-27 1-19-18-28 4-23-22-24-7-14-24 15-19-13-16zM232 252l24 5 23 29 12 42-7 33 22 44-2 36-18 35-17-22-4-34-19-27-9-42-18-29 10-29-21-15z"/><path class="flat-land" d="M304 45l21-16 34 5 18 19-6 21-28 7-24-10z"/><path class="flat-land" d="M449 137l15-11 25 6 8 13-9 15-25 4-16-11zM436 177l24-12 25 18 7 32-12 25 10 36-6 37-21 35-17-22 3-36-16-35 9-39-9-22z"/><path class="flat-land" d="M500 145l24-14 23 4 15-13 23 3 17 16 28-4 22 7 28-12 35 9 25 16 35 0 18 16-12 15-29 3-25 16-31-1-25 17-32-4-24 15-22-12-19 8-25-15-21 6-18-20 6-19-18-14zM644 229l21 8 11 22-8 29-19 8-13-18 3-28z"/><path class="flat-land" d="M798 350l34-16 37 6 33 22 6 29-23 26-39 8-29-15-18-28z"/><path class="flat-isle" d="M358 212l8-6 11 5-3 10-12 1zM393 202l7-4 8 7-5 8-9-3zM409 231l5-3 5 4-4 6-6-2zM867 177l7-4 7 5-4 7-8-1zM904 205l7-4 5 7-6 6-7-3zM911 232l5-2 4 4-4 5-5-2z"/><path class="flat-shore" d="M31 256c97-29 185-19 275 7s179 38 270 13 179-40 265-13 110 24 126 17M32 305c111 23 209 16 300-6s175-17 260 7 193 32 377-4"/>`;
renderWorldBoard();
function selectPage(page){document.querySelectorAll('.page').forEach(section=>section.classList.toggle('active',section.id===page));document.querySelectorAll('.tab').forEach(tab=>tab.classList.toggle('active',tab.dataset.page===page));if(page==='world')renderWorldBoard();close()}
document.querySelector('.memory-drop summary').textContent='Open a memory';
photos=function(files){const status=document.querySelector('#upload-status');const valid=[];const rejected=[];[...files].forEach(file=>{if(!acceptedPhotoTypes.has(file.type))rejected.push(file.name+' is not a supported image.');else if(file.size>maxPhotoBytes)rejected.push(file.name+' is larger than 8 MB.');else valid.push(file)});if(status)status.textContent=rejected.length?rejected.join(' '):'';valid.forEach(file=>{const reader=new FileReader();reader.onload=()=>document.querySelector('#photos').insertAdjacentHTML('beforeend','<img alt="Memory photograph" src="'+reader.result+'">');reader.onerror=()=>{if(status)status.textContent=file.name+' could not be added. Please try another image.'};reader.readAsDataURL(file)})};
const memoryDrop=document.querySelector('.memory-drop'),memorySamples=document.querySelector('#memory-samples');function renderMemorySamples(){const all=[...houses.filter(h=>h[8]).flatMap(h=>h[11]),...Object.values(notes).flat()];memorySamples.innerHTML=all.sort(()=>Math.random()-.5).slice(0,3).map(note=>'<p>'+escape(note)+'</p>').join('')}memoryDrop.addEventListener('toggle',()=>{if(memoryDrop.open)renderMemorySamples()});renderMemorySamples();
houses.forEach((h,i)=>{const b=document.createElement('button');b.className='stamp '+h[3]+(h[8]?' earned':'');b.style.setProperty('--tilt',[-4,3,-2,2,-3,4,-2,3,-3,2][i]+'deg');b.setAttribute('aria-label','Open '+h[0]+' '+(h[8]?'archive':'discovery'));b.innerHTML=(h[8]?'<i class="tape tl"></i><i class="tape tr"></i><i class="tape bl"></i><i class="tape br"></i>':'')+'<div class="stamp-photo" style="background-image:url('+h[9]+')"></div><div class="stamp-inner"><small>'+h[1]+'</small><strong>'+h[4]+'</strong><span>'+h[0]+'</span><small>'+h[2]+'</small></div>';b.onclick=()=>openHouse(h,b);grid.appendChild(b)});
function openHouse(h,from){current=h;trigger=from;seal.textContent=h[4];document.querySelector('#dossier-kicker').textContent=(h[8]?'YOUR HOUSE ARCHIVE':'A HOUSE TO DISCOVER')+' · '+h[1];document.querySelector('#dossier-title').textContent=h[0];document.querySelector('#affirm').textContent='“'+h[7]+'”';if(h[8]){const ns=[...h[11],...(notes[h[0]]||[])];content.innerHTML='<section class="archive-intro"><span class="eyebrow">Your moments</span><p>'+ns.length+' memories · 1 House scene</p></section><section class="memory-section"><p class="retention">Prototype note: notes are saved on this device only.</p><div id="memories">'+ns.map(n=>'<p class="memory">'+escape(n)+'</p>').join('')+'</div><textarea id="note" aria-label="Write a memory for this House" placeholder="Capture a moment you want to keep…"></textarea><button class="save" id="save">Keep this memory ↗</button></section><section class="photo-section"><p class="retention">Prototype note: photos remain only for this browser session.</p><div class="photos" id="photos"><div class="memory-image"><img src="'+h[9]+'" alt="'+h[0]+' House scene"><span><a class="source" target="_blank" rel="noreferrer" href="'+h[10]+'">House scene — © Soho House</a></span></div></div><label class="photo-slot">＋ Add a photograph<input id="file" type="file" accept="image/*" multiple></label></section>'+discovery(h);document.querySelector('#save').onclick=save;document.querySelector('#file').onchange=e=>photos(e.target.files)}else{content.innerHTML='<div class="hero" style="background-image:url('+h[9]+')"><span>'+h[5]+'</span></div>'+discovery(h)+'<button class="just-visited" id="justVisited">I just visited</button><p class="help">This creates a prototype stamp, then opens your archive.</p>';document.querySelector('#justVisited').onclick=()=>claimVisit(h,from)}dossier.classList.add('show');document.querySelector('#close').focus()}
function claimVisit(h,from){dossier.classList.remove('show');from.classList.add('becoming-earned');from.insertAdjacentHTML('afterbegin','<i class="tape tl arriving"></i><i class="tape tr arriving"></i><i class="tape bl arriving"></i><i class="tape br arriving"></i>');const tapes=[...from.querySelectorAll('.tape.arriving')];tapes.forEach((tape,index)=>setTimeout(()=>tape.classList.add('applied'),180+index*180));setTimeout(()=>{h[8]=true;h[2]='JUST VISITED';h[3]='oxblood';from.classList.remove('blank');from.classList.add('oxblood');document.querySelector('#found').textContent=String(houses.filter(x=>x[8]).length).padStart(2,'0');from.classList.remove('becoming-earned');from.classList.add('earned');from.setAttribute('aria-label','Open '+h[0]+' archive');from.querySelector('.stamp-inner small:last-child').textContent='JUST VISITED';openHouse(h,from);content.insertAdjacentHTML('afterbegin','<section class="arrival-cta"><span class="eyebrow">Stamp received</span><h3>Make this one yours.</h3><p>Keep the people, the detail or the feeling before it slips away.</p><p class="arrival-session">Prototype stamp — saved only for this browser session.</p><div class="arrival-actions"><button id="arrivalMemory">Add a memory</button><button id="arrivalPhoto">Add a photo</button></div></section>');document.querySelector('#arrivalMemory').onclick=()=>document.querySelector('#note').focus();document.querySelector('#arrivalPhoto').onclick=()=>document.querySelector('#file').click()},1120)}
function discovery(h){return '<section class="discovery"><span class="eyebrow">At this House</span><h3>'+h[5]+'</h3><p>'+h[6]+'</p><ul class="amenities">'+h[12].map(a=>'<li>'+a+'</li>').join('')+'</ul><a class="source" target="_blank" rel="noreferrer" href="'+h[10]+'">Official source: Soho House ↗</a><span class="verified">Reviewed July 2026</span></section>'}
function save(){const field=document.querySelector('#note'),value=field.value.trim();if(!value)return;notes[current[0]]=[...(notes[current[0]]||[]),value];localStorage.setItem('soho-passport-notes',JSON.stringify(notes));document.querySelector('#memories').insertAdjacentHTML('beforeend','<p class="memory">'+escape(value)+'</p>');field.value='';document.querySelector('#memory-count').textContent=String(9+Object.values(notes).flat().length).padStart(2,'0')}
function photos(files){[...files].forEach(file=>{const reader=new FileReader();reader.onload=()=>document.querySelector('#photos').insertAdjacentHTML('beforeend','<img alt="Memory photograph" src="'+reader.result+'">');reader.readAsDataURL(file)})}
function close(){dossier.classList.remove('show');shell.inert=false;shell.removeAttribute('aria-hidden');trigger&&trigger.focus()}document.querySelector('#close').onclick=close;window.addEventListener('keydown',e=>{if(e.key==='Escape'&&dossier.classList.contains('show'))close()});document.querySelectorAll('[data-page]').forEach(button=>button.onclick=()=>selectPage(button.dataset.page));document.querySelector('#open').onclick=()=>{renderCityStamps();book.classList.add('opening');cover.classList.add('open');document.querySelector('.world').classList.remove('is-cover')};document.querySelector('#back').onclick=()=>{close();book.classList.remove('opening');cover.classList.remove('open');document.querySelector('.world').classList.add('is-cover')};
